export const nodes = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    age: 28,
    city: "New York",
    address: "Hellow",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    age: 32,
    city: "Los Angeles",
    address: "Hellow",
  },
  {
    id: 3,
    name: "Mike Johnson",
    email: "mike@example.com",
    age: 25,
    city: "Chicago",
    address: "Hellow",
  },
  {
    id: 4,
    name: "Sarah Wilson",
    email: "sarah@example.com",
    age: 29,
    city: "Houston",
    address: "Hellow",
  },
  {
    id: 5,
    name: "David Brown",
    email: "david@example.com",
    age: 35,
    city: "Phoenix",
    address: "Hellow",
  },
  {
    id: 6,
    name: "John Doe",
    email: "john@example.com",
    age: 28,
    city: "New York",
    address: "Hellow",
  },
  {
    id: 7,
    name: "Jane Smith",
    email: "jane@example.com",
    age: 32,
    city: "Los Angeles",
    address: "Hellow",
  },
  {
    id: 8,
    name: "Mike Johnson",
    email: "mike@example.com",
    age: 25,
    city: "Chicago",
    address: "Hellow",
  },
  {
    id: 9,
    name: "Sarah Wilson",
    email: "sarah@example.com",
    age: 29,
    city: "Houston",
    address: "Hellow",
  },
  {
    id: 10,
    name: "David Brown",
    email: "david@example.com",
    age: 35,
    city: "Phoenix",
    address: "Hellow",
  },
  {
    id: 11,
    name: "John Doe",
    email: "john@example.com",
    age: 28,
    city: "New York",
    address: "Hellow",
  },
  {
    id: 12,
    name: "Jane Smith",
    email: "jane@example.com",
    age: 32,
    city: "Los Angeles",
    address: "Hellow",
  },
  {
    id: 13,
    name: "Mike Johnson",
    email: "mike@example.com",
    age: 25,
    city: "Chicago",
    address: "Hellow",
  },
  {
    id: 14,
    name: "Sarah Wilson",
    email: "sarah@example.com",
    age: 29,
    city: "Houston",
    address: "Hellow",
  },
  {
    id: 15,
    name: "David Brown",
    email: "david@example.com",
    age: 35,
    city: "Phoenix",
    address: "Hellow",
  },
];
