export const nodes = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    age: 28,
    city: "New York",
    address: "123 Broadway Street, Apt 4B",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    age: 32,
    city: "Los Angeles",
    address: "456 Sunset Boulevard",
  },
  {
    id: 3,
    name: "Mike Johnson",
    email: "mike@example.com",
    age: 25,
    city: "Chicago",
    address: "789 Michigan Avenue",
  },
  {
    id: 4,
    name: "Sarah Wilson",
    email: "sarah@example.com",
    age: 29,
    city: "Houston",
    address: "321 Main Street, Suite 100",
  },
  {
    id: 5,
    name: "David Brown",
    email: "david@example.com",
    age: 35,
    city: "Phoenix",
    address: "654 Desert Road",
  },
  {
    id: 6,
    name: "Emily Davis",
    email: "emily@example.com",
    age: 27,
    city: "Philadelphia",
    address: "987 Liberty Bell Lane",
  },
  {
    id: 7,
    name: "Robert Miller",
    email: "robert@example.com",
    age: 31,
    city: "San Antonio",
    address: "147 Riverwalk Drive",
  },
  {
    id: 8,
    name: "Jessica Garcia",
    email: "jessica@example.com",
    age: 26,
    city: "San Diego",
    address: "258 Ocean View Terrace",
  },
  {
    id: 9,
    name: "Christopher Lee",
    email: "chris@example.com",
    age: 33,
    city: "Dallas",
    address: "369 Cowboy Trail",
  },
  {
    id: 10,
    name: "Amanda Rodriguez",
    email: "amanda@example.com",
    age: 30,
    city: "San Jose",
    address: "741 Silicon Valley Blvd",
  },
  {
    id: 11,
    name: "James Anderson",
    email: "james@example.com",
    age: 24,
    city: "Austin",
    address: "852 Music City Lane",
  },
  {
    id: 12,
    name: "Lisa Taylor",
    email: "lisa@example.com",
    age: 34,
    city: "Jacksonville",
    address: "963 Sunshine Avenue",
  },
  {
    id: 13,
    name: "Kevin Thomas",
    email: "kevin@example.com",
    age: 28,
    city: "Fort Worth",
    address: "159 Stockyard Street",
  },
  {
    id: 14,
    name: "Michelle White",
    email: "michelle@example.com",
    age: 29,
    city: "Columbus",
    address: "267 University Drive",
  },
  {
    id: 15,
    name: "Steven Martin",
    email: "steven@example.com",
    age: 36,
    city: "Charlotte",
    address: "375 Banking District Plaza",
  },
];
